### ISSUE TITLE
List of problems

### ISSUE THREAD

**Issue by TheMadmanofChaos** [soundlogic2236/Silva#2]
Played around a bit with the mod, list of what I've found.

Crash after killing a creaper, had a paradox item with enchantments in my inventory. http://pastebin.com/pQMmt31S . Had a sword, enchanted with Bane of Arthropods and unbreaking, I recall.

The particles used in the enchant transfer cause a huge amount of FPS lag.

Boom moss, when when spreading, can override non solid blocks and tile entities.

The Mana Eater doesn't function correctly, not giving mana to adjacent pools.

I'd change the color of dwarven entries, they are hard to separate from normal entries.

Further testing must be done on the other aspects of this mod. I will report other issues as I find them tomorrow, and mention them in IRC or here.

**Comment by soundlogic2236** [comment]
I... think? I may have fixed the first one while trying to fix a different crash. Can you confirm that boom moss causes an issue on the latest? I can't seem to reproduce it. As for the mana eater-are you trying it on a guilty mana pool? It can't take from those, since I'm checking how much mana is actually removed.

**Comment by soundlogic2236** [comment]
I cut down on the particles on the enchant transfer, though I can't confirm if it fixes it since I seem to handle it fine. Can you suggest a color for the dwarven entries (one of the minecraft color codes)

**Comment by The0x539** [comment]
Brown?

**Comment by soundlogic2236** [comment]
No such color code. http://minecraft.gamepedia.com/Formatting_codes#Color_codes

**Comment by TheMadmanofChaos** [comment]
I'd go with gold, personally, for Dwarven texts. I'll redownload the mod then check these issues again.

**Comment by soundlogic2236** [comment]
I believe all of these have now been resolved.
